### ISSUE TITLE
Documentation for the examples

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/php-library-glpi#19]
Hi, @Naylin15 

Could you add a README.md file in the example folder with the information about how to install and run the example?

Thanks

**Comment by ajsb85** [comment]
Hi, @DIOHz0r 

Could you help @Naylin15 with this task?
Later she can improve it, with a proper template for all api-client examples.

Thanks.

**Comment by DIOHz0r** [comment]
Hi @ajsb85, Please close this issue
