### ISSUE TITLE
Create project site

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/php-library-glpi#2]
Hi, @Gianfranco97   

Could you create the project site of this repository?
Using the theme of GLPI Network (blue)

Thanks

**Comment by ajsb85** [comment]
Hi, @Gianfranco97 

Here you can get information about the package from composer
https://packagist.org/packages/glpi-project/php-library-glpi.json

Useful information to build the project site. 👌

**Comment by ajsb85** [comment]
Hi, @Gianfranco97 

The project site is not up to date.
I cannot see the new content of the index.

I think the cache version needs change.

Thanks.

**Comment by ajsb85** [comment]
Hi, @DIOHz0r 

Please, take a look in the project site, to see what we can improve 👍 

https://glpi-project.github.io/php-library-glpi/

Thanks.

**Comment by Gianfranco97** [comment]
Hi, @ajsb85 

Yes, it must be that, the code is already updated.
