### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/php-library-glpi#20]
Hi, @DIOHz0r 

I will put here all possible errors for the library.

**Comment by ajsb85** [comment]
Handle error when no dependencies are installed

`require_once __DIR__ . '/../vendor/autoload.php';`

Reference:
https://stackoverflow.com/questions/8261756/how-to-catch-error-of-require-or-include-in-php

**Comment by ajsb85** [comment]
"Cannot connect to api" is a general message. The API reply with a proper message, please use it.

Reference: https://git.io/vFvSp

**Comment by ajsb85** [comment]
Create a custom error messages when it's not provided by the API

**Comment by DIOHz0r** [comment]
> Handle error when no dependencies are installed

This is not a normal practice in PHP, when a file is not included or the class is not founded PHP will throw an error by default.

**Comment by btry** [comment]
This is a library. Something will depend on it and the library will depend on others. 

This is Composer's task to guarantee to our lib that all dependencies are available. I agree to delegate to Composer.
