### ISSUE TITLE
Code documentation

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/php-library-glpi#22]
Hi, @Naylin15 

Could you write the documentation of the code?
And please share with us the feedback to merge in all client libraries common error messages.

Thanks.

**Comment by ajsb85** [comment]
Hi, @DIOHz0r 

Could you put the code documentation site into the gh-pages branch using Travis CI?
Update this documentation in every push of the develop branch.
Please, coordinate with @Gianfranco97 

Thanks.

**Comment by DIOHz0r** [comment]
Hi @ajsb85, Please add the missing GH_TOKEN to the repo ,travis' dashboard and close this issue

**Comment by ajsb85** [comment]
Hi, @DIOHz0r 
Already added the personal token from the user @flyve-mdm-bot 👍

**Comment by ajsb85** [comment]
Hi, @DIOHz0r 
The code documentation still blank.
https://glpi-project.github.io/php-library-glpi/docs/

Could you @Gianfranco97 review the workflow to see if the cache of the PWA is updated in every push of the develop branch?

**Comment by ajsb85** [comment]
Hi, @DIOHz0r
Fyi, the code documentation return 404.

**Comment by ajsb85** [comment]
Hi, @DIOHz0r 

The actual URL is:
https://glpi-project.github.io/php-library-glpi/build/docs/develop/
But you deploy the code documentation in:
https://glpi-project.github.io/php-library-glpi/build/docs/master/

I will normalize these paths for all project sites.
