### ISSUE TITLE
Wrong package name for composer

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/php-library-glpi#26]
Hi, @DIOHz0r 

Please, fix the name of the composer package

Thanks.

https://github.com/glpi-project/php-library-glpi/blob/develop/composer.json#L2

**Comment by DIOHz0r** [comment]
Why this wasn't closed if the PR was merged?

**Comment by ajsb85** [comment]
`close issue #26`

It is not a keyword for the regex

https://help.github.com/articles/closing-issues-using-keywords/
