### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/php-library-glpi#34]
Hi, @DIOHz0r 

Put the report into the gh-pages branch.

Thanks.

/cc @Gianfranco97

**Comment by DIOHz0r** [comment]
Hi @ajsb85, Please add the missing GH_TOKEN to the repo ,travis' dashboard and close this issue

**Comment by ajsb85** [comment]
Hi, @DIOHz0r 
Already added the personal token from the user @flyve-mdm-bot 👍

**Comment by ajsb85** [comment]
Hi, @DIOHz0r 
The code coverage still blank.
https://glpi-project.github.io/php-library-glpi/coverage/

Could you @Gianfranco97 review the workflow to see if the cache of the PWA is updated in every push of the develop branch?
