### ISSUE TITLE
Client API REST for GLPI 

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/php-library-glpi#5]
Hi, @btry and @DIOHz0r    

This is the main task, create the Composer package for the GLPI API REST.
Generic for any project in the future.

**Comment by ajsb85** [comment]
Hi, @DIOHz0r  

Please check the features completed and finish asap the remaining features of the last workshop

- [ ] killSession
- [ ] getMyProfiles
- [ ] getActiveProfile
- [ ] changeActiveProfile
- [ ] getMyEntities
- [ ] getActiveEntities
- [ ] changeActiveEntities
- [ ] getFullSession
- [ ] getAnItem
- [ ] getAllItems
- [ ] getSubItems
- [ ] getMultipleItems
- [ ] listSearchOptions
- [ ] searchItems
- [ ] addItem
- [ ] addItems
- [ ] lostPassword
- [ ] updateItem
- [ ] updateItems
- [ ] deleteItem
- [ ] deleteItems

**Comment by DIOHz0r** [comment]
Hi @ajsb85 ,

These are my endPoints done so far...

- [x] killSession 
- [x] getMyProfiles 
- [x] getActiveProfile 
- [x] changeActiveProfile 
- [x] getMyEntities 
- [x] getActiveEntities 
- [x] changeActiveEntities 
- [x] getFullSession 
- [x] getAnItem 
- [x] getAllItems 
- [x] getSubItems 
- [x] getMultipleItems 
- [x] listSearchOptions 
- [x] searchItems 
- [x] addItem 
- [x] addItems 
- [x] lostPassword 
- [x] updateItem 
- [x] updateItems 
- [x] deleteItem 
- [x] deleteItems

**Comment by DIOHz0r** [comment]
There are still missing the search endpoints, the rest of the endpoint were done and merged, Will still be this issue open?

**Comment by ajsb85** [comment]
Yes, lets discuss here main points about the library, and you can close this issue with a reference in a PR when all endpoints are merged into the develop branch.

**Comment by DIOHz0r** [comment]
This issue can be closed because the library implements all those endpoints listed (checked on #47)
