### ISSUE TITLE
Wrong menu link for documentation

### ISSUE THREAD

**Issue by DIOHz0r** [glpi-project/php-library-glpi#55]
### Observed Results:

The code documentation link of the project site has the wrong URL. 
  
### Expected behavior:

The correct link for the menu is the develop folder (https://glpi-project.github.io/php-library-glpi/build/docs/develop/)

**Comment by ajsb85** [comment]
Hi, @Naylin15 
Could you fix it?
Thanks.

**Comment by Naylin15** [comment]
Right away
