### ISSUE TITLE
Publish to Composer

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/php-library-glpi#6]
Hi, @DIOHz0r 

You need to integrate the task in Travis CI to publish the package to Packagist.
The script will run in every push of the master branch.

Thanks

**Comment by DIOHz0r** [comment]
Hi @ajsb85,

For the record when I try to submit the repo I got this message.

> The vendor is already taken by someone else. You may ask them to add your package and give you maintainership access. If they add you as a maintainer on any package in that vendor namespace, you will then be able to add new packages in that namespace. The packages already in that vendor namespace can be found at glpi-project

**Comment by ajsb85** [comment]
@DIOHz0r Dont publish the repo at the moment, we need to discuss with the core team to see if they accept or we need to create a new vendor like "teclib"

**Comment by trasher** [comment]
Done: https://packagist.org/packages/glpi-project/php-library-glpi
